name: Glitch Sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Glitch Project
      uses: kanadgupta/glitch-sync@main
      with:
        project-id: '${{ secrets.PROJECT_ID }}' # glitch process_env.PROJECT_ID
        auth-token: '${{ secrets.IMPORT_AUTHORIZATION }}' # glitch import 'Authorization' request header
        path: 'app'
        