name: Glitch Sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Glitch Project
      uses: kanadgupta/glitch-sync@main
      with:
        project-id: '${{ secrets.projectId }}' # glitch process_env.PROJECT_ID
        auth-token: '${{ secrets.authToken }}' # glitch process_env.PROJECT_INVITE_TOKEN
        path: 'app'